Models/ConfiguracaoEstacionamento.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EstacionamentoMVC.Models
{
    public class ConfiguracaoEstacionamento
    {
        public int Id { get; set; }
        public decimal ValorInicial { get; set; } = 0;
        public decimal ValorPorHora { get; set; } = 0;
        public decimal ValorMensalidade { get; set; } = 0;
    }
}

Models/ErrorViewModel.cs
namespace EstacionamentoMVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/RegistroEstacionamento.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EstacionamentoMVC.Models
{
    public class RegistroEstacionamento
    {
        public int Id { get; set; }
        public int VeiculoId { get; set; }
        public DateTime DataEntrada { get; set; }
        public DateTime? DataSaida { get; set; }
        public decimal? Valor { get; set; }

        public virtual Veiculo Veiculo { get; set; }
    }
}

Models/Veiculo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EstacionamentoMVC.Models
{
    public class Veiculo
    {
        public int Id { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Placa { get; set; }
    }
}

Controllers/ConfiguracaoEstacionamentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EstacionamentoMVC.Context;
using EstacionamentoMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace EstacionamentoMVC.Controllers
{
    public class ConfiguracaoEstacionamentoController : Controller
    {
        private readonly EstacionamentoContext _context;

        public ConfiguracaoEstacionamentoController(EstacionamentoContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var configuracao = _context.ConfiguracaoEstacionamentos.FirstOrDefault();
            return View(configuracao);
        }

        [HttpPost]
        public IActionResult Atualizar(ConfiguracaoEstacionamento configuracao)
        {
            if (ModelState.IsValid)
            {
                var c = _context.ConfiguracaoEstacionamentos.Find(configuracao.Id);
                c.ValorInicial = configuracao.ValorInicial;
                c.ValorPorHora = configuracao.ValorPorHora;
                c.ValorMensalidade = configuracao.ValorMensalidade;

                _context.ConfiguracaoEstacionamentos.Update(c);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using EstacionamentoMVC.Models;

namespace EstacionamentoMVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/RegistroEstacionamentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EstacionamentoMVC.Context;
using EstacionamentoMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;

namespace EstacionamentoMVC.Controllers
{
    public class RegistroEstacionamentoController : Controller
    {
        private readonly EstacionamentoContext _context;

        public RegistroEstacionamentoController(EstacionamentoContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var veiculos = _context.Veiculos.AsQueryable();
            ViewBag.Veiculos = _context.Veiculos.ToList();
            var estacionamento = _context.RegistroEstacionamento.ToList();
            return View(estacionamento);
        }

        [HttpPost]
        public IActionResult Index(int? veiculoId)
        {
            var v = _context.Veiculos.Find(veiculoId);

            if (ModelState.IsValid && v != null)
            {
                var registro = new RegistroEstacionamento
                {
                    VeiculoId = v.Id,
                    DataEntrada = DateTime.Now
                };

                _context.RegistroEstacionamento.Add(registro);
                _context.SaveChanges();
            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Validar()
        {
            return View();
        }

        public IActionResult PesquisarPorPlaca(string placa)
        {
            var veiculo = _context.Veiculos
                .FirstOrDefault(p => p.Placa.Contains(placa));

            if (veiculo != null)
            {
                return RedirectToAction("ValidarEstacionamento", new { veiculoId = veiculo.Id });
            }

            return RedirectToAction("Index");
        }

        public IActionResult ValidarEstacionamento(int veiculoId)
        {
            var registro = _context.RegistroEstacionamento
            .Where(r => r.VeiculoId == veiculoId)
            .FirstOrDefault();

            if (registro == null) return NotFound();

            var configuracao = _context.ConfiguracaoEstacionamentos.FirstOrDefault();

            if (configuracao == null) return NotFound();

            TimeSpan tempoEstacionado = DateTime.Now - registro.DataEntrada;
            int horas = (int)tempoEstacionado.TotalHours;

            registro.Valor = horas * configuracao.ValorPorHora + configuracao.ValorInicial;

            return View("Validar", registro);
        }

    }
}

Controllers/VeiculoController.cs
using EstacionamentoMVC.Context;
using EstacionamentoMVC.Models;
using Microsoft.AspNetCore.Mvc;


namespace EstacionamentoMVC.Controllers
{
    public class VeiculoController : Controller
    {
        private readonly EstacionamentoContext _context;

        public VeiculoController(EstacionamentoContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var veiculos = _context.Veiculos.ToList();
            return View(veiculos);
        }

        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(Veiculo veiculo)
        {
            if (ModelState.IsValid)
            {
                _context.Veiculos.Add(veiculo);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }

            return View(veiculo);
        }

        [HttpPost]
        public IActionResult Deletar(int id)
        {
            var v = _context.Veiculos.Find(id);
            _context.Remove(v);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Editar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Editar(Veiculo v)
        {
            var vBanco = _context.Veiculos.Find(v.Id);

            if (vBanco == null)
            {
                return NotFound();
            }

            vBanco.Marca = v.Marca;
            vBanco.Modelo = v.Modelo;
            vBanco.Placa = v.Placa;

            _context.Veiculos.Update(vBanco);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

Views/ConfiguracaoEstacionamento/Index.cshtml
@model EstacionamentoMVC.Models.ConfiguracaoEstacionamento

@{
    ViewData["Title"] = "Configuracao";
}

<h1>Configuração</h1>

<form asp-action="Atualizar" method="post">
    <input type="hidden" asp-for="Id" />

    <div class="mb-3">
        <label asp-for="ValorPorHora" class="form-label"></label>
        <input asp-for="ValorPorHora" class="form-control" />
    </div>

    <div class="mb-3">
        <label asp-for="ValorMensalidade" class="form-label"></label>
        <input asp-for="ValorMensalidade" class="form-control" />
    </div>

    <div class="mb-3">
        <label asp-for="ValorInicial" class="form-label"></label>
        <input asp-for="ValorInicial" class="form-control" />
    </div>

    <button type="submit" class="btn btn-primary">Salvar</button>
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="text-center">
    <h1 class="display-4">Estacionamento</h1>

</div>
<div style="grid-template-columns: 1fr 1fr; height: 70vh;     justify-content: center;" class="d-grid gap-3 text-center">
    <a asp-controller="Veiculo" asp-action="Index" class="card p-2 bg-primary text-white">Veículos</a>
    <a asp-controller="RegistroEstacionamento" asp-action="Index" class="card p-2">Estacionar</a>
    <a asp-controller="RegistroEstacionamento" asp-action="Index" class="card p-2">Estacionar</a>
    <a asp-controller="RegistroEstacionamento" asp-action="Index" class="card p-2">Estacionar</a>
</div>

Views/RegistroEstacionamento/Index.cshtml
@model IEnumerable<EstacionamentoMVC.Models.RegistroEstacionamento>

@{
    ViewData["Title"] = "Registrar Entrada";
    var veiculos = ViewBag.Veiculos as List<Veiculo>;
}

<form asp-action="Index" method="post">
    <select name="veiculoId" class="form-select">
        @foreach (var v in veiculos)
        {
            <option value="@v.Id">@v.Modelo - @v.Placa</option>
        }
    </select>
    <button type="submit" class="btn btn-success mt-2">Registrar Entrada</button>
</form>

<br>
<form asp-controller="RegistroEstacionamento" asp-action="PesquisarPorPlaca">
    <input type="text" name="placa" class="form-control" placeholder="Buscar por placa" />
    <button type="submit" class="btn btn-primary mt-2">Buscar</button>
</form>
<br>

<div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Veículo</th>
                <th>Entrada</th>
                <th>Saída</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var registro in Model)
            {
                <tr>
                    <td>@(registro.Veiculo?.Modelo) - @(registro.Veiculo?.Placa)</td>
                    <td>@registro.DataEntrada.ToString("dd/MM/yyyy HH:mm")</td>
                    <td>
                        <a asp-controller="RegistroEstacionamento" asp-action="ValidarEstacionamento"
                            asp-route-veiculoId="@registro.VeiculoId">Validar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/RegistroEstacionamento/Validar.cshtml
@model EstacionamentoMVC.Models.RegistroEstacionamento

@{
    ViewData["Title"] = "Validar estacionamento";
}

<p>Total a pagar</p>
<p>@Model.Valor</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Estacionamento</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EstacionamentoMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Estacionamento</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item"></li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="ConfiguracaoEstacionamento" asp-action="Index">Configuracão</a>
                        </li>
                    </ul>
                </div>
            </div>z
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - EstacionamentoMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Veiculo/Cadastrar.cshtml
@model EstacionamentoMVC.Models.Veiculo;

@{
    ViewData["Title"] = "Cadastro";
}

<a class="btn btn-primary" asp-action="Index">Voltar</a>
<h1 style="margin-top: 2rem;">Cadastro</h1>

<form asp-action="Cadastrar">
  <div class="mb-3">
    <label asp-for="Marca" class="form-label">Marca</label>
    <input class="form-control" asp-for="Marca">
  </div>
  <div class="mb-3">
    <label asp-for="Modelo" class="form-label">Modelo</label>
    <input class="form-control" asp-for="Modelo">
  </div>
    <div class="mb-3"></div>
    <label asp-for="Placa" class="form-label">Placa</label>
    <input class="form-control" asp-for="Placa">
  </div>

   <input type="submit" value="Criar" class="btn btn-primary"/>
</form>

Views/Veiculo/Editar.cshtml
@model EstacionamentoMVC.Models.Veiculo;

@{
    ViewData["Title"] = "Editar";
}

<a class="btn btn-primary" asp-action="Index">Voltar</a>
<h1>Editar</h1>

<form asp-action="Editar">
  <div class="mb-3">
    <label asp-for="Marca" class="form-label">Marca</label>
    <input class="form-control" asp-for="Marca">
  </div>
  <div class="mb-3">
    <label asp-for="Modelo" class="form-label">Modelo</label>
    <input class="form-control" asp-for="Modelo">
  </div>
    <div class="mb-3"></div>
    <label asp-for="Placa" class="form-label">Placa</label>
    <input class="form-control" asp-for="Placa">
  </div>

   <input type="submit" value="Editar" class="btn btn-primary"/>
</form>

Views/Veiculo/Index.cshtml
@model IEnumerable<EstacionamentoMVC.Models.Veiculo>

@{
    ViewData["Title"] = "Veículos";
}

<a asp-controller="Home" asp-action="Index">Pagina inicial</a>
<h1>Veículos</h1>

<div class="text-center mb-3">
    <a asp-action="Cadastrar" class="btn btn-primary">+ Cadastrar</a>
</div>

@if (Model != null && Model.Any())
{
    <table class="table table-hover">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.First().Id)</th>
                <th>@Html.DisplayNameFor(model => model.First().Marca)</th>
                <th>@Html.DisplayNameFor(model => model.First().Modelo)</th>
                <th>@Html.DisplayNameFor(model => model.First().Placa)</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var v in Model)
            {
                <tr>
                    <td>@v.Id</td>
                    <td>@v.Marca</td>
                    <td>@v.Modelo</td>
                    <td>@v.Placa</td>
                    <td>
                        <form asp-action="Deletar" method="post">
                            @Html.AntiForgeryToken()
                            <input type="hidden" name="id" value="@v.Id" />
                            <input type="submit" value="Excluir" class="btn btn-danger btn-sm" />
                        </form>
                    </td>
                    <td>
                        <button class="btn btn-warning btn-sm" data-bs-toggle="modal" data-bs-target="#editarModal-@v.Id">
                            Editar
                        </button>
                        <div class="modal fade" id="editarModal-@v.Id" tabindex="-1" aria-labelledby="editarModalLabel-@v.Id"
                            aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <form asp-action="Editar" method="post">
                                        @Html.AntiForgeryToken()
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="editarModalLabel-@v.Id">Editar Veículo</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                aria-label="Fechar"></button>
                                        </div>
                                        <div class="modal-body">
                                            <input type="hidden" name="Id" value="@v.Id" />
                                            <div class="mb-3">
                                                <label>Marca</label>
                                                <input type="text" name="Marca" class="form-control" value="@v.Marca" />
                                            </div>
                                            <div class="mb-3">
                                                <label>Modelo</label>
                                                <input type="text" name="Modelo" class="form-control" value="@v.Modelo" />
                                            </div>
                                            <div class="mb-3">
                                                <label>Placa</label>
                                                <input type="text" name="Placa" class="form-control" value="@v.Placa" />
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary"
                                                data-bs-dismiss="modal">Cancelar</button>
                                            <button type="submit" class="btn btn-success">Salvar</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="text-center mt-4">
        <p>Não há veiculos cadastrados</p>
    </div>
}